### ISSUE TITLE
Only full stars possible?

### ISSUE THREAD

**Issue by Kubik-Rubik** [nashio/star-rating-svg#1]
Hey @nashio,

is it possible to use only full stars? I'm thinking about implementing your script in one plugin for Joomla! but I need only full stars instead of half stars.

Thank you in advance!

Greetings

**Comment by nashio** [comment]
Howdy, I added another setting to use full stars, use it like:
```
$(".your-stars").starRating({  
    useFullStars: true
});
```

Let me know

**Comment by Kubik-Rubik** [comment]
Works as described. Thank you!
