### ISSUE TITLE
readonly

### ISSUE THREAD

**Issue by binskeep** [nashio/star-rating-svg#10]
Hi Nashio,

Just to let you know, I had to change a line of your code in the 'addListeners:' function from 'if( this.settings.read**O**nly ){ return; }' to 'if( this.settings.read**o**nly ){ return; }'.  readonly with lower cap o is defined in your default definition.

I appreciate you taking care of this.  I like your software.

**Comment by nashio** [comment]
hi @binskeep , thanks for pointing that out, my typo was actually in the settings section.
