### ISSUE TITLE
Removing last full star

### ISSUE THREAD

**Issue by LindenerGenie** [nashio/star-rating-svg#11]
When activating full stars it is not possible to return to zero stars.

Attached a small change that allows to remove a star by clicking it again.
This works for all stars, especially the first star.

Git Patch-File:
[commit-f69811d.txt](https://github.com/nashio/star-rating-svg/files/321262/commit-f69811d.txt)

**Comment by nashio** [comment]
Hi, fixed setting the left most star to zero when using full stars. 
It was basically an offset issue.
I really want to keep the option of only setting to zero when you click on the left-most area btw.

**Comment by LindenerGenie** [comment]
Thank you!
