### ISSUE TITLE
Editing rating

### ISSUE THREAD

**Issue by mcpat1993** [nashio/star-rating-svg#13]
Hi, maybe I missed it, but I didn't notice anywhere that you can edit the rating. When you click on a star then it makes the callback but destroys the listeners to make the same thing happen. I was looking for something that on hover shows the stars you are about to select but when not hovering has the last callbacked grade. Is there a way that I can do that?

**Comment by nashio** [comment]
Hi,
Is this what your looking for?
Using the option *disableAfterRate : false* will not destroy the listeners once you click,
and the using the method *$('.your-selector').starRating('getRating')* will get the last rating that you clicked on.

**Comment by mcpat1993** [comment]
Perfect! Thank you very much.
