### ISSUE TITLE
Change starSize

### ISSUE THREAD

**Issue by Ygnaaac** [nashio/star-rating-svg#14]
It woud be great to have method for changing star size, or even better add breakpoints to options, so user can set size for different resolutions.

**Comment by nashio** [comment]
Those are really good ideas, I'm gonna look into it.
thx

**Comment by nashio** [comment]
Hey, added a new method to resize the stars:
    $('your-selector').starRating('resize', 50)
Let me know if it works for you.

As for including an option to detect breakpoints in the plugin itself, I think I'm gonna leave it simple for now. Maybe in the future, if more people ask for it.

**Comment by Ygnaaac** [comment]
Hi, I just tried this new method and it works perfectly. Exactly what I needed.
Thank you
