### ISSUE TITLE
Problem with tag base

### ISSUE THREAD

**Issue by sibprojects** [nashio/star-rating-svg#16]
When in head I have tag `<base href="/site/" />` and whe url of page is not /site/, but like: /site/category/
rating din't work. It's show nothing.
Can you fix this? Tnx.

**Comment by nashio** [comment]
Can you upload your code to a repo?, I'd like to see your implementation.
The only file that the plugin loads externally is the CSS. I'd make sure that is being loaded correctly.
The plugin itself doesn't depend on paths, but I'd still like to see what you have.
Thanks

**Comment by sibprojects** [comment]
Ok, I make example for you:
1. all work koorectly because base href = to path: [http://tmp.sibprojects.com/parfum/]
2. din't work copy of file: [http://tmp.sibprojects.com/parfum/card.html]

**Comment by sibprojects** [comment]
Big thanks!!!!!!
