### ISSUE TITLE
how to change the option after load?

### ISSUE THREAD

**Issue by apzkr** [nashio/star-rating-svg#17]
Hello,

When I load the starRating, 
sometimes I want to change the option (readOnly, strokeColor.. etc).

So, after load the starRating, I typing like this,
" $('element').starRating({readOnly: true}); "
but not working.

how to change the option after load?

**Comment by nashio** [comment]
Oh, thats because readOnly and strokeColor are "options" not methods. They're used when initializing. What are you trying to achieve?

I could add a 'readOnly' method, I can see this being useful. But not sure if it would be that useful to add method to change the strokeColor on the fly.

**Comment by apzkr** [comment]
Thanks for quick reply!

I need readOnly method, and strokeColor is just an example.

Could you add a 'readOnly' method?

**Comment by nashio** [comment]
Sure, I'll get back to you

**Comment by nashio** [comment]
This is how you disable manually:

    $('.your-selector').starRating('setReadOnly', true);

or back to normal

    $('.your-selector').starRating('setReadOnly', false);
