### ISSUE TITLE
Bug in Firefox when stars were not filled if baseUrl contains local anchor on page

### ISSUE THREAD

**Issue by serhiyzablotskiy** [nashio/star-rating-svg#19]
Hi. I has detected a bug in firefox when stars were not filled if baseUrl contains local anchor on page.

I had resolved this issue by removing #local_anchor in my baseUrl before it will display.

 var baseUrl = s.baseUrl ? location.href : '';

baseUrl = baseUrl.indexOf('#') != -1? baseUrl.replace(baseUrl.substring(baseUrl.indexOf('#'), baseUrl.length), ""): baseUrl;

...

**Comment by nashio** [comment]
Hey @serhiyzablotskiy ,
have you tried the option mentioned here?
https://github.com/nashio/star-rating-svg/issues/16

`{
   baseUrl: true
}`

**Comment by serhiyzablotskiy** [comment]
Hello. Yes I had try. But it didn't work.

2017-01-04 7:00 GMT+02:00 Ignacio Chavez <notifications@github.com>:

**Comment by nashio** [comment]
Ah, I see what you mean, apologize, I misunderstood your comment.
I added a fix, please re-download and let me know if that fixes it
I basically only grab the part before the "#" from the url, similar to what you did.
