### ISSUE TITLE
Improvement - Unbind event listeners after click

### ISSUE THREAD

**Issue by Kubik-Rubik** [nashio/star-rating-svg#2]
Hi @nashio,

I have another suggestion. In my plugin I do an Ajax request to save to rating to the database. After the user has clicked, the state should change to read-only.

I could solve it like this while testing:

```
removeListeners: function(){
    this.$stars.off();
},
```

then I call it in applyRating:

```
applyRating: function(e){
    var index = this.getIndex(e);
    var rating = index + 1;

    // paint selected and remove hovered color
    this.paintStars(index, 'active');
    this.executeCallback( rating, this.$el );
    this._state.rating = rating;


    this.removeListeners();
},
```
Could you add this feature to the script (controllable with a parameter)?

Thank you!

Viktor

**Comment by nashio** [comment]
Added, thanks for the suggestion

check option: "disableAfterRate"

its on by default

**Comment by Kubik-Rubik** [comment]
Wow, that was fast. Works great, thank you for the fast update!
