### ISSUE TITLE
Doesn't work in Microsoft Edge

### ISSUE THREAD

**Issue by nanhapy** [nashio/star-rating-svg#21]
[screen shot](http://7xjsf0.com1.z0.glb.clouddn.com/star-rating.png)

**Comment by nashio** [comment]
Thanks, will look into this

**Comment by nashio** [comment]
@nanhapy what version of Microsoft Edge are you using? I'm using 38.14

**Comment by nanhapy** [comment]
That's really wired.  i'm using Microsoft Edge 38.14393.1066.0.

**Comment by nashio** [comment]
Do you see any errors in the console?

**Comment by nanhapy** [comment]
Yeah! I got some errors:
```
SCRIPT5009: '$' is undefined
demo (193,1)
SCRIPT5009: 'jQuery' is undefined
jquery.star-rating-svg.js (10,3)
```

**Comment by nashio** [comment]
Gotcha, so make sure jQuery is loaded before this plugin

**Comment by nanhapy** [comment]
jquery is not loaded. [screenshot](http://ocuvhk0qh.bkt.clouddn.com/network.png)

**Comment by nashio** [comment]
Refer to the usage part https://github.com/nashio/star-rating-svg 
so you load jQuery before the plugin
