### ISSUE TITLE
Is it possible to use the greater value of star to be shown???

### ISSUE THREAD

**Issue by Nageshwar** [nashio/star-rating-svg#29]
Hello Team,

I would like to show the Star values in this pattern

> 0.0 till <= 0.5: 0.5 filled star
> 0.5 till <= 1.0: 1.0 filled star
> 1.0 till <= 1.5: 1.5 filled stars
> 1.5 till <= 2.0: 2.0 filled stars
> 2.0 till <= 2.5: 2.5 filled stars
> 2.5 till <= 3.0: 3 filled stars
> 3.0 till <= 3.5: 3.5 filled stars
> 3.5 <= 4.0: 4 filled stars
> 4.0 till <= 4.5: 4.5 filled stars
> 4.5 till <= 5: 5 filled stars

Is it possible to do that in this manner???

please reply asap that would be very helpful

Thanks 
Nageshwar Jha

**Comment by nashio** [comment]
Hi @Nageshwar , not sure I follow. Isn't that what its happening right now?
for ex. if I hover from 2.0 to 2.5 then 2.5 stars will be filled.
please elaborate, thank you

**Comment by Nageshwar** [comment]
Hello @nashio ,

I would like to Show the intial rating of star when the value will be 4.7 then the star will be 5 prefilled as  please check screenshot.

![screenshot_22](https://user-images.githubusercontent.com/3288042/34034126-2ca748de-e1a3-11e7-8409-e1bf8f6c2cb7.png)

but what actually happening is for 4.7 star the image shows 4.5 stars

**Comment by nashio** [comment]
I see, on initial load then. Yeah right now its rounding down, you need up.
hm, I'm thinking maybe of adding an option to round both ways, could be useful.

**Comment by Nageshwar** [comment]
Yes but half rounding will be great (Y)

For example 4.1 should be 4.5 not 5.

Thanks @nashio

**Comment by nashio** [comment]
yeah thats what I meant actually, 4.1 -> 4.5, instead of 4.0

**Comment by Nageshwar** [comment]
Yes 

That will be great (y)

Thanks in Advance

**Comment by nashio** [comment]
@Nageshwar   
download the newest version and use the option, ```forceRoundUp: true```. 
check the readme for reference: https://github.com/nashio/star-rating-svg/blob/master/README.md
let me know if that works for you

**Comment by Nageshwar** [comment]
Great (y)

Thanks , I will surely let you know.

**Comment by Nageshwar** [comment]
Yes it worked perfectly for my test rating 4.7 it shows 5
