### ISSUE TITLE
get attribute this

### ISSUE THREAD

**Issue by hoangnamitc** [nashio/star-rating-svg#33]
Hi,
I want get value data attribute of this to set readOnly from db.
ext:
![image](https://user-images.githubusercontent.com/7042462/42008658-ed31ad78-7ab0-11e8-88f1-5f03cea5b93d.png)

![image](https://user-images.githubusercontent.com/7042462/42008766-65008266-7ab1-11e8-96e9-5b25dca1a426.png)

but not read value?
What do i do?
tks

**Comment by nashio** [comment]
Do you want to read it from a DB?, how are you rendering your pages?
You have several options depending on what you're most familiar with.
You can server render the value in a JS variable and use it as a setting, 
or you can also wait until your server call is done loading and then initialize the plugin
If you still need help let me know more details about your setup

**Comment by hoangnamitc** [comment]
I want read data of attribute initial plugin.
eg: 
`<div class="my-rating" data-init="3" data-readonly="true"></div>`

how to me can get attribute data: init, readonly for parameters of plugin ? tks

**Comment by greeninho** [comment]
hoangnamitc try this:

<div class="my-rating" data-init="3" data-readonly="true"></div>

js
`$(".my-rating").starRating({
        starSize: 15,
        callback: function(currentRating, $el) {
            // make a server call here
            value = $($el).data('init');
}
})
`

**Comment by hoangnamitc** [comment]
@greeninho Thanks you answer, but function callback run when you click rating, I want get data from attribute of element for do parameter for starRating();
i'm can not do it.

**Comment by TheGeekyM** [comment]
You can use this js file instead

[](https://github.com/nashio/star-rating-svg/pull/45/commits/bf89be00fc4efb5e0b93448a888c45c60d41ba36
)
and in your code you should do like this:
                                   `     <div class="my-rating" data-readonly="{{$order->rate ? true : false}}" data-rating="{{$order->rate}}"  id="{{$order->id}}"></div>`
