### ISSUE TITLE
Can only input once

### ISSUE THREAD

**Issue by sugat009** [nashio/star-rating-svg#35]
Users can't edit it once input

**Comment by jarrin** [comment]
set disableAfterRate to false in your settings object.

**Comment by neoburgos** [comment]
Yes, but if you set
disableAfterRate: false
and then vote 4 (for example) and after it you vote 2 (for example), stars color don't change and it fixes on 4, not 2.
You can check it in 'disableAfeterRate' example y your demo web: http://nashio.github.io/star-rating-svg/demo/
