### ISSUE TITLE
Demo broken

### ISSUE THREAD

**Issue by flaviocopes** [nashio/star-rating-svg#4]
`Mixed Content: The page at 'https://nashio.github.io/star-rating-svg/demo/' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.
nashio.github.io/:184 Uncaught ReferenceError: $ is not defined`

**Comment by nashio** [comment]
Thanks!
