### ISSUE TITLE
Stars not displayed

### ISSUE THREAD

**Issue by abderrahmaneMustapha** [nashio/star-rating-svg#46]
i cant see the stars when i use arabic language : 
<img width="555" alt="Capture" src="https://user-images.githubusercontent.com/34008130/76706580-c0202780-66e8-11ea-94d5-88327ce9533a.PNG">

its work when i use english language : 
<img width="309" alt="Capture_" src="https://user-images.githubusercontent.com/34008130/76706596-cadabc80-66e8-11ea-9063-e809f22e7158.PNG">

**Comment by nashio** [comment]
Can you put a live example so we can check whats going on

**Comment by abderrahmaneMustapha** [comment]
@nashio  thank you, but I already solved this i just added dir="ltr" to the stars container 
 here is the  live example: dzstartups.com
